# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
                ('section_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='subjects.Grade')),
            ],
        ),
    ]
